[
  {
    recipeName: "Chicken Biryani",
    recipeImage: "https://i.ibb.co.com/YFKMfySP/filename.png",
    category: "Rice",
    cuisineType: "Bangladeshi",
    difficultyLevel: "Hard",
    preparationTime: 90,
    ingredients: [
      "Chicken",
      "Basmati Rice",
      "Yogurt",
      "Onion",
      "Biryani Masala",
    ],
    instructions:
      "Marinate the chicken, cook the rice separately, layer everything together, and steam until fully cooked.",
    authorId: "user_001",
    authorName: "Rashidul Islam",
    authorEmail: "rashid@gmail.com",
    likesCount: 245,
    favoriteCount: 68,
    status: "approved",
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-07-10T10:00:00.000Z",
    price: 12,
  },
  {
    recipeName: "Beef Burger",
    recipeImage: "https://i.ibb.co.com/M5nwFf0w/burger.png",
    category: "Burger",
    cuisineType: "American",
    difficultyLevel: "Easy",
    preparationTime: 30,
    ingredients: [
      "Beef Patty",
      "Burger Bun",
      "Cheddar Cheese",
      "Lettuce",
      "Tomato",
    ],
    instructions:
      "Grill the beef patty, toast the bun, and assemble with vegetables and cheese.",
    authorId: "user_002",
    authorName: "John Smith",
    authorEmail: "john@gmail.com",
    likesCount: 180,
    favoriteCount: 55,
    status: "approved",
    createdAt: "2026-07-09T09:30:00.000Z",
    updatedAt: "2026-07-09T09:30:00.000Z",
    price: 10,
  },

  {
    recipeName: "Margherita Pizza",
    recipeImage: "https://i.ibb.co.com/r26yPxn0/pizza.png",
    category: "Pizza",
    cuisineType: "Italian",
    difficultyLevel: "Medium",
    preparationTime: 45,
    ingredients: ["Pizza Dough", "Mozzarella", "Tomato Sauce", "Basil"],
    instructions:
      "Spread tomato sauce, add mozzarella and basil, then bake until golden.",
    authorId: "user_003",
    authorName: "Luca Rossi",
    authorEmail: "luca@gmail.com",
    likesCount: 312,
    favoriteCount: 75,
    status: "approved",
    createdAt: "2026-07-08T08:00:00.000Z",
    updatedAt: "2026-07-08T08:00:00.000Z",
    price: 15,
  },

  {
    recipeName: "Sushi Roll",
    recipeImage: "https://i.ibb.co.com/pjjf75fx/roll.png",
    category: "Seafood",
    cuisineType: "Japanese",
    difficultyLevel: "Hard",
    preparationTime: 60,
    ingredients: ["Sushi Rice", "Nori", "Salmon", "Cucumber", "Avocado"],
    instructions:
      "Roll rice, salmon, cucumber and avocado in nori, then slice.",
    authorId: "user_004",
    authorName: "Ken Watanabe",
    authorEmail: "ken@gmail.com",
    likesCount: 275,
    favoriteCount: 82,
    status: "approved",
    createdAt: "2026-07-07T12:00:00.000Z",
    updatedAt: "2026-07-07T12:00:00.000Z",
    price: 20,
  },
  {
    recipeName: "Pad Thai",
    recipeImage: "https://i.ibb.co.com/Zpc4crxv/pad.png",
    category: "Noodles",
    cuisineType: "Thai",
    difficultyLevel: "Medium",
    preparationTime: 35,
    ingredients: ["Rice Noodles", "Shrimp", "Egg", "Bean Sprouts", "Peanuts"],
    instructions: "Stir-fry noodles with shrimp, egg, vegetables and sauce.",
    authorId: "user_005",
    authorName: "Somchai",
    authorEmail: "somchai@gmail.com",
    likesCount: 194,
    favoriteCount: 49,
    status: "approved",
    createdAt: "2026-07-06T11:20:00.000Z",
    updatedAt: "2026-07-06T11:20:00.000Z",
    price: 11,
  },

  {
    recipeName: "Caesar Salad",
    recipeImage: "https://i.ibb.co.com/dwF78XCr/pad-1.png",
    category: "Salad",
    cuisineType: "Italian",
    difficultyLevel: "Easy",
    preparationTime: 20,
    ingredients: ["Lettuce", "Croutons", "Parmesan", "Caesar Dressing"],
    instructions: "Mix lettuce with dressing, croutons and parmesan cheese.",
    authorId: "user_006",
    authorName: "Emily Brown",
    authorEmail: "emily@gmail.com",
    likesCount: 121,
    favoriteCount: 36,
    status: "approved",
    createdAt: "2026-07-05T10:15:00.000Z",
    updatedAt: "2026-07-05T10:15:00.000Z",
    price: 8,
  },

  {
    recipeName: "Butter Chicken",
    recipeImage: "https://i.ibb.co.com/s9ndrLhw/pad-2.png",
    category: "Chicken",
    cuisineType: "Indian",
    difficultyLevel: "Medium",
    preparationTime: 50,
    ingredients: ["Chicken", "Butter", "Cream", "Tomato", "Spices"],
    instructions: "Cook marinated chicken and simmer in creamy tomato sauce.",
    authorId: "user_007",
    authorName: "Raj Kumar",
    authorEmail: "raj@gmail.com",
    likesCount: 288,
    favoriteCount: 90,
    status: "approved",
    createdAt: "2026-07-04T09:00:00.000Z",
    updatedAt: "2026-07-04T09:00:00.000Z",
    price: 14,
  },

  {
    recipeName: "Chocolate Cake",
    recipeImage: "https://i.ibb.co.com/m53Rrg2x/cack.png",
    category: "Dessert",
    cuisineType: "French",
    difficultyLevel: "Medium",
    preparationTime: 70,
    ingredients: ["Flour", "Cocoa Powder", "Eggs", "Sugar", "Butter"],
    instructions: "Mix ingredients, bake, then frost with chocolate cream.",
    authorId: "user_008",
    authorName: "Sophie Martin",
    authorEmail: "sophie@gmail.com",
    likesCount: 356,
    favoriteCount: 102,
    status: "approved",
    createdAt: "2026-07-03T08:30:00.000Z",
    updatedAt: "2026-07-03T08:30:00.000Z",
    price: 18,
  },

  {
    recipeName: "Pancakes",
    recipeImage: " https://i.ibb.co.com/sprjnM9g/cack-1.png",
    category: "Breakfast",
    cuisineType: "American",
    difficultyLevel: "Easy",
    preparationTime: 25,
    ingredients: ["Flour", "Milk", "Egg", "Butter", "Maple Syrup"],
    instructions: "Prepare batter, cook on a hot pan and serve with syrup.",
    authorId: "user_009",
    authorName: "Olivia Taylor",
    authorEmail: "olivia@gmail.com",
    likesCount: 142,
    favoriteCount: 41,
    status: "approved",
    createdAt: "2026-07-02T07:45:00.000Z",
    updatedAt: "2026-07-02T07:45:00.000Z",
    price: 7,
  },

  {
    recipeName: "Grilled Salmon",
    recipeImage: " https://i.ibb.co.com/Fbx3SbpL/cack-2.png",
    category: "Seafood",
    cuisineType: "Norwegian",
    difficultyLevel: "Medium",
    preparationTime: 40,
    ingredients: ["Salmon", "Olive Oil", "Garlic", "Lemon", "Herbs"],
    instructions: "Season salmon and grill until perfectly cooked.",
    authorId: "user_010",
    authorName: "Erik Hansen",
    authorEmail: "erik@gmail.com",
    likesCount: 210,
    favoriteCount: 59,
    status: "approved",
    createdAt: "2026-07-01T06:50:00.000Z",
    updatedAt: "2026-07-01T06:50:00.000Z",
    price: 22,
  },

  {
    recipeName: "Tacos",
    recipeImage: "https://i.ibb.co.com/cXw5dxLn/filename-2.png",
    category: "Fast Food",
    cuisineType: "Mexican",
    difficultyLevel: "Easy",
    preparationTime: 25,
    ingredients: ["Tortilla", "Ground Beef", "Cheese", "Lettuce", "Tomato"],
    instructions: "Cook beef, fill tortillas with toppings and serve.",
    authorId: "user_011",
    authorName: "Carlos Gomez",
    authorEmail: "carlos@gmail.com",
    likesCount: 199,
    favoriteCount: 63,
    status: "approved",
    createdAt: "2026-06-30T10:10:00.000Z",
    updatedAt: "2026-06-30T10:10:00.000Z",
    price: 9,
  },

  {
    recipeName: "Spaghetti Carbonara",
    recipeImage: " https://i.ibb.co.com/1fxKJQrq/filename-1.png",
    category: "Pasta",
    cuisineType: "Italian",
    difficultyLevel: "Medium",
    preparationTime: 35,
    ingredients: ["Spaghetti", "Egg", "Parmesan", "Bacon", "Black Pepper"],
    instructions: "Cook pasta, mix with eggs, cheese and crispy bacon.",
    authorId: "user_012",
    authorName: "Marco Bianchi",
    authorEmail: "marco@gmail.com",
    likesCount: 267,
    favoriteCount: 80,
    status: "approved",
    createdAt: "2026-06-29T09:15:00.000Z",
    updatedAt: "2026-06-29T09:15:00.000Z",
    price: 13,
  },
];
